### PR TITLE
Create course.zip on the fly with GitHub Action

### LINKED ISSUE #38: Generate `course.zip` via CI pipeline -> Link ZIP file
Currently `course.zip` is included in the repo as a binary file, which makes its contents a bit opaque to git and GitHub. Alternatively, we could generate it (e.g. from a subfolder in the repo) as part of the CI pipeline which would make it somewhat easier to work with.

### PR DESCRIPTION
**Pull request by alexdewar**
I think this should work :wink:. My only concern is that the generated course.zip will not be served along with the Jekyll pages.

One possible fix/hack (if this is the case) would be to deposit `course.zip` into `_site` where presumably Jekyll will be able to find it.

Closes #38.

### CODE REVIEW

**Review by dalonsoa — APPROVED** [review]
This looks good and I think it will help maintaining and making changes to the example code. Having said that, if the generated `course.zip` file cannot be accessed by anyone, then it won't be that useful.

Maybe your suggestion would work. Another possibility is to create a release, upload the zip file there and somewhat indicate in the course material to download the file from the latest release.

**Review by cc-a — CHANGES_REQUESTED** [review]
Hmm yeah, the problem is that the copy of the site deployed is not the one in the Jekyll workflow. The copy of the site deployed is from the `pages-build-deployment` workflow which is a automated github thing. The workflow in `jekyll.yml` was from back when the github pages thing was a mysterious magic that we had no visibility of. So we had a build workflow so we could see errors to debug.

In order to move to using the build from this workflow we'd have to change our [publishing source] and add the `upload-pages-artifact` action to publish from our built copy. But that should work pretty well I think.

[publishing source]: https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

**Comment by alexdewar** [comment]
Our grad school discussion today reminded me that I still have this open... Maybe a better approach is to move to using a GitHub Action as suggested by @cc-a? Then we wouldn't need to do any Jekyll/Ruby magic, just generate the zip file as part of the workflow.

What do y'all reckon?

**Comment by alexdewar** [comment]
Superseded by #46

**Pull request closed without merging**
